---
title: "Week 3 - Quiz"
author: "Pedro Boareto"
date: "24/07/2020"
output: html_document
---

```{r}
library(stringr); library(stringi); library(tm); library(wordcloud); library(ggplot2)
```
#Question 1
```{r}
Q1<-NextWordIs("a case of ", "([Aa]+ +[Cc]ase+ +[Oo]f+ +[^ ]+ )" )
Q1
```

#Question 2
```{r}
Q2<-NextWordIs("would mean the ", "([Ww]ould+ +[Mm]ean+ +[Tt]he+ +[^ ]+ )" )  
Q2
```

#Question 3
```{r}
Q3<-NextWordIs("make me the ", "([Mm]ake+ +[Mm]e+ +[Tt]he+ +[^ ]+ )" )  
Q3
```

#Question 4
```{r}
Q4A<-NextWordIs("struggling ", "([Ss]truggling+ +[^ ]+ +[^ ]+ +[^ ]+ )" )  
Q4A
Q4B<-NextWordIs("struggling ", "([Ss]truggling+ +[^ ]+ +[^ ]+ )" )  
Q4B
Q4C<-NextWordIs("struggling ", "([Ss]truggling+ +[^ ]+ )" )  
Q4C
#defense
```

#Question 5
```{r}
Q5<-NextWordIs("date at the ", "([Dd]ate+ +[Aa]t+ +[Tt]he+ +[^ ]+ )" )  
Q5
#beach
```

#Question 6
```{r}
Q6<-NextWordIs("be on my ", "([Bb]e+ +[Oo]n+ +[Mm]y+ +[^ ]+ )" )  
Q6
```

#Question 7
```{r}
Q7<-NextWordIs("quite some ", "([Qq]uite+ +[Ss]ome+ +[^ ]+ )" )  
Q7
```

#Question 8
```{r}
Q8<-NextWordIs("his little ", "([Hh]is+ +[Ll]ittle+ +[^ ]+ )" )  
Q8  
```

#Question 9
```{r}
Q9<-NextWordIs("during the ", "([Dd]uring+ +[TT]he+ +[^ ]+ )" )  
Q9  
```

#Question 10
```{r}
Q10<-NextWordIs("must be ",  "([Mm]ust+ +[Bb]e+ +[^ ]+ )" )  
Q10  
```
